#!/bin/bash

if [ -z $1 ] ; then
  echo "Usage: $0 [start|stop|restart] "
  exit 1
fi

# Source the common setup functions for startup scripts
test -r /etc/rc.common || exit 1
. /etc/rc.common

# Set up some defaults

BASE_DIR='/usr/local/mongodb'

#
# SHARD A
#
A_DATA="${BASE_DIR}/db/a"
A_LOG="${BASE_DIR}/log/a.log"
A_PORT=10000

#
# SHARD B
#
B_DATA="${BASE_DIR}/db/b"
B_LOG="${BASE_DIR}/log/b.log"
B_PORT=10001

#
# CONFIG SERVER
#
CNF_DATA="${BASE_DIR}/db/config"
CNF_LOG="${BASE_DIR}/log/config.log"
CNF_PORT=20000

#
# ROUTING SERVER
#
RTN_DATA="${BASE_DIR}/db/routing"
RTN_LOG="${BASE_DIR}/log/routing.log"
RTN_PORT=27017

StartService(){
	${BASE_DIR}/bin/mongod --rest --shardsvr --dbpath $A_DATA --logpath $A_LOG --port $A_PORT > /dev/null 2>&1 &
	${BASE_DIR}/bin/mongod --rest --shardsvr --dbpath $B_DATA --logpath $B_LOG --port $B_PORT > /dev/null 2>&1 &
	sleep 2
	${BASE_DIR}/bin/mongod --rest --configsvr --dbpath $CNF_DATA --logpath $CNF_LOG --port $CNF_PORT > /dev/null 2>&1 &
	sleep 2
	${BASE_DIR}/bin/mongos --configdb localhost:$CNF_PORT --pidfilepath $RTN_DATA/mongod.lock --logpath $RTN_LOG --port $RTN_PORT > /dev/null 2>&1 &
}

#
# DATA PORT
#
_StopService() {
	pid=
	pidfile=$1/mongod.lock

	# If the lockfile exists, it contains the PID
	if [ -e $pidfile ]; then
		pid=`cat $pidfile`
	fi

	# If we don't have a PID, check for it
	if [ "$pid" == "" ]; then
		pid=`/usr/sbin/lsof -i tcp:$2 | tail -1 | awk '{print $2}'`
	fi

	# If we've found a PID, let's kill it
	if [ "$pid" != "" ]; then
		kill -15 $pid
	fi
}

StopService() {
	_StopService $RTN_DATA $RTN_PORT
	_StopService $CNF_DATA $CNF_PORT
	_StopService $B_DATA $B_PORT
	_StopService $A_DATA $A_PORT
}

RestartService() {
	StopService
	sleep 3
	StartService
}

RunService $1
